### ISSUE TITLE
Wrong slash on Windows computer with JavaScript

### ISSUE THREAD

**Issue by bearmc27** [ericbiewener/vscode-vandelay#14]
While importing, different OS results differently

Linux computer: 
e.g.
`import GlobalStyle from "../static/style/GlobalStyle";`

Windows computer (Windows 10 for me):
e.g.
`import GlobalStyle from "..\static\style\GlobalStyle";`

This is a common issue of VSCode, which "Copy Path" return system-dependents style of path. It would be great if you can add an option to replace two different slash (Mainly Windows style to Linux Style. NodeJS use Linux Style btw)

**Comment by ericbiewener** [comment]
Ok, just published a new version that should fix this. I don't have a Windows computer to test on, so let me know if it doesn't work. Should be just be a simple string replace call, so hopefully I didn't botch it :)

FYI, the [`processImportPath`](https://github.com/ericbiewener/vscode-vandelay#processimportpathimportpath-string-absimportpath-string-activefilepath-string-projectroot-string-string) config option lets you modify the import path that will get written to the file, so this could actually solve the Windows slash issue. I only point that out to make you aware of that config option in case you weren't already. In this particular case you raised, Vandelay should do the right thing on its own with Windows paths, which is why I pushed a fix.

Going to close the issue, but just leave another comment if my fix doesn't work.

**Comment by bearmc27** [comment]
FYI, the update works perfectly.
