### ISSUE TITLE
Activating extension failed (unresponsive extension host)

### ISSUE THREAD

**Issue by dpuscher** [ericbiewener/vscode-vandelay#16]
Since the update to version 2, the extension stopped working for me.
When looking at the developer console in vscode I see that the config is loaded and the js-language is registered:
```
console.ts:134 [Extension Host] Loading vandelay config file from [...]/vandelay-js.js
console.ts:134 [Extension Host] Loading vandelay config file from [...]/vandelay-py.js
console.ts:134 [Extension Host] /Users/dpuscher/Library/Application Support/Code/User/workspaceStorage/4c2d0b4a8e874580716d175b3dd9a75b/edb.vandelay
console.ts:134 [Extension Host] Vandelay language registered: js
```

But then the extension takes very long to initialize and finally fails to load:
```
WARN UNRESPONSIVE extension host, 'edb.vandelay' took 94% of 1344.042ms, saved PROFILE here: '/var/folders/_5/wvz0ll8n2k9by5_59h67_f240000gn/T/exthost-5763c0.cpuprofile' (6) [{…}, {…}, {…}, {…}, {…}, {…}]
Activating extension 'edb.vandelay' failed: Cannot read property 'imp' of undefined.
```

Is there anything I can do to from my side to make the extension work again?

**Comment by ericbiewener** [comment]
Weird. Have you tried simply uninstalling and reinstalling the extension? If that doesn't work:

1. The error message says that it saved a file named `exthost-5763c0.cpuprofile`. Can you attach that file to a comment?
2. That same line seems to be printing out an array of 6 objects. What do those objects contain?
3. Does the `Cannot read property 'imp' of undefined.` error point to a specific line number?

**Comment by dpuscher** [comment]
I already tried uninstalling and reinstalling the extension but still no luck.

1. Here is the cpu profile file:
[exthost-87807c.cpuprofile.txt](https://github.com/ericbiewener/vscode-vandelay/files/3129312/exthost-87807c.cpuprofile.txt)

2. The array contains these 6 objects:
```
0: {id: "edb.vandelay", total: 10359927, percentage: 95}
1: {id: "gc", total: 42518, percentage: 0}
2: {id: "program", total: 171747, percentage: 2}
3: {id: "self", total: 322943, percentage: 3}
4: {id: "shinnn.stylelint", total: 3927, percentage: 0}
5: {id: "wix.vscode-import-cost", total: 11373, percentage: 0}
```
3.  
```
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'imp' of undefined
	at U (/Users/dpuscher/.vscode/extensions/edb.vandelay-2.4.0/dist/extension.js:342:9685)
	at module.exports.e.then.e (/Users/dpuscher/.vscode/extensions/edb.vandelay-2.4.0/dist/extension.js:342:12306)
```

I hope, this helps you to identify the problem. If you need any information just let me know.

**Comment by ericbiewener** [comment]
Is this project in a public repo that I could pull down to see if I can recreate the issue? Otherwise, can you try creating a new project and dropping a `vandelay-js.js` in there to see if it still occurs? I'm just trying to see if it's a problem. You're facing more broadly or just on this project.

Another thing to try is simply deleting any files you find inside `/Users/dpuscher/Library/Application Support/Code/User/workspaceStorage/4c2d0b4a8e874580716d175b3dd9a75b/edb.vandelay`. That's where the extended stores the available import data for your workspace.

Sorry that I can't pinpoint yet what's going on!

**Comment by dpuscher** [comment]
I finally got it working. It was due to the settings in my `vandelay.js` file.
Somehow the Extension stops working when you add the whole root directory as an include path:
```
includePaths: [__dirname],
```
But I am not really sure which file caused this behavior. When adding the mentioned setting to a new project with just one js-file the extension works.

I will open source my project soon and maybe you might want look into which file causes the extension to break.
Anyway I am very happy the extension is working again. Also, thank you very much for your excellent support. 👏

**Comment by ericbiewener** [comment]
Glad you figured it out! Looking at the code, I'm not sure why `[__dirname]` would cause a problem. When the extension activates, it automatically caches all your project's imports if it doesn't find a pre-existing cache file. My guess is the issue was occurring during that stage of the process. Perhaps there is a way to do that work without VS Code considering it as part of the extension activation process.

I'll close this ticket for now, but please comment here again if you do end up open sourcing your project. I'd love to investigate further!
