### ISSUE TITLE
Import command error: [exthost] [error] SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by maxfi** [ericbiewener/vscode-vandelay#27]
Visual Studio Code info:
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

Please note that I'm using the [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) extension to work on a remote linux VM. Not sure if that matters...

Extension error:

```
[exthost] [error] SyntaxError: Unexpected token u in JSON at position 0
	at JSON.parse (<anonymous>)
	at j (/home/ubuntu/.vscode-server/extensions/edb.vandelay-4.2.0/dist/extension.js:8:26216)
	at j (/home/ubuntu/.vscode-server/extensions/edb.vandelay-4.2.0/dist/extension.js:8:25937)
	at k (/home/ubuntu/.vscode-server/extensions/edb.vandelay-4.2.0/dist/extension.js:8:26173)
	at Object.finalizeCacheLanguage (/home/ubuntu/.vscode-server/extensions/edb.vandelay-4.2.0/dist/extension.js:8:37542)
	at se (/home/ubuntu/.vscode-server/extensions/edb.vandelay-4.2.0/dist/extension.js:8:50547)
```

`vandelay-js.js` 
```js
/* eslint-disable */
const path = require('path')

/**
 * Configuration file for VS Code Vandelay extension.
 * https://github.com/ericbiewener/vscode-vandelay#configuration
 */

module.exports = {
  // This is the only required property. At least one path must be included.
  includePaths: [
    path.join(__dirname, 'imports/utils'),
  ],
}
```

The `imports/utils` dir only contains 3 js files.

**Comment by ericbiewener** [comment]
Not sure if Remote - SSH is the culprit. Was it working for you for a while before running into this issue? The error you're receiving stems from the extension trying to read a file with bad JSON (the file that contains a cache of your projects exports). Since bad JSON in that file shouldn't be possible in theory, I'd be interested to know what's in it. Ultimately, just deleting the file will will be the solution. Follow these steps:

1. Open your project in VS Code
2. Run the command "Toggle Developer Tools"
3. Switch to the console in the dev tools window
4. You should see a log item that says `Vandelay activating`, followed by a log of an object. Expand that object to find the `storagePath` key.
5. The file you're looking for will be that path + `vandelay-v2-<js|py>.json`
6. Try just `cat <filepath>` to see what the file contains. That might give us some indication about whether it is a Remote SSH issue
7. Delete that file and then try running the Vandelay command `Cache Project Exports`
8. Open a file with some exports and simply re-save it. If Vandelay doesn't error, then it was able to successfully parse the newly generated cache file.
